# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        "/:title"

# Setup
title:            205 Reset
tagline:          'The story of a man resetting life.'
url:              http://205reset.com
shorturl:         205reset.com

author:
  name:           '205 Reset'
  url:            https://twitter.com/205reset

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/205reset/205reset.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  RSS: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
